# A dictionary mapping common technology aliases to standardized canonical names.
# Keys are lowercased for ease of case-insensitive lookup.
SKILL_ALIASES = {
    "react": "React",
    "react.js": "React",
    "reactjs": "React",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "k8s": "Kubernetes",
    "kubernetes": "Kubernetes",
    "docker": "Docker",
    "node": "Node.js",
    "node.js": "Node.js",
    "nodejs": "Node.js",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "vue": "Vue.js",
    "vue.js": "Vue.js",
    "vuejs": "Vue.js",
    "angular": "Angular",
    "angularjs": "Angular",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "aws": "Amazon Web Services",
    "amazon web services": "Amazon Web Services",
    "gcp": "Google Cloud Platform",
    "google cloud": "Google Cloud Platform",
    "google cloud platform": "Google Cloud Platform",
    "fastapi": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "python": "Python",
    "py": "Python",
    "golang": "Go",
    "go": "Go",
    "rust": "Rust",
    "cpp": "C++",
    "c++": "C++",
    "html": "HTML",
    "html5": "HTML",
    "css": "CSS",
    "css3": "CSS",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "sass": "Sass",
    "scss": "Sass",
    "git": "Git",
    "github": "Git",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "aws lambda": "AWS Lambda",
    "lambda": "AWS Lambda",
    "sql": "SQL",
    "mysql": "MySQL",
    "sqlite": "SQLite",
    "dynamodb": "DynamoDB",
    "graphql": "GraphQL",
    "rest": "REST API",
    "rest api": "REST API",
    "restful": "REST API",
    "pytorch": "PyTorch",
    "tensorflow": "TensorFlow",
    "tf": "TensorFlow",
    "keras": "Keras",
    "scikit-learn": "Scikit-Learn",
    "sklearn": "Scikit-Learn",
    "numpy": "NumPy",
    "pandas": "Pandas"
}

def normalize_skill(skill_name: str) -> str:
    """
    Normalizes a skill name using the alias dictionary.
    Returns the standardized name if found, otherwise returns the original name stripped.
    """
    cleaned = skill_name.strip()
    return SKILL_ALIASES.get(cleaned.lower(), cleaned)
